version: "3"
networks:
  openbanking-networking:
    driver: bridge
services:
  openbanking:
    container_name: openbanking
    image: openbanking
    ports:
      - 9001:9001
      - 8080:8080
    networks:
      - openbanking-networking